### ISSUE TITLE
Support in-editor markers by default

### ISSUE THREAD

**Issue by clint-stripe** [damolinx/vscode-bookmarks#3]
The [April 2023 release](https://code.visualstudio.com/updates/v1_78#_glyph-margin-decoration-rendering-improvements) improved support for multiple in-editor glyphs; the bookmark icon is now visible _alongside_ any breakpoint markers.

A setting to enable these markers by default (rather than manually toggling each time) would be great!

**Comment by damolinx** [comment]
v0.4.3 adds a new configuration setting: _Bookmarks: Marker > Show by Default_ that "Controls whether bookmark markers are rendered by default at startup".  The setting is intentionally only configurable as a "User" setting (it would seem odd having any given workspace change the behavior).

When verifying this I did notice a few issues with markers that I will fix on next release (e.g. folders are not properly supported, wrapped lines end on multiple makers being rendered). Also, some odd behaviors with VS Code itself (sometimes the double-lane behavior would stop working, or breakpoint glyphs would end up in both lanes).  Still, I assume that you would prefer the feature now rather than later.
