### ISSUE TITLE
What is the specific file path for saving bookmarks?

### ISSUE THREAD

**Issue by oranger-lc** [damolinx/vscode-bookmarks#4]
What is the specific file path for saving bookmarks? I need to backup this file, these bookmarks are too important to me.

This extension is very satisfying to me, thank you！

**Comment by damolinx** [comment]
Hi @oranger-lc, glad you are finding the extension useful.

I [use](https://github.com/damolinx/vscode-bookmarks/blob/master/src/datastore/mementoDatastore.ts#L64) VSCode's [Memento](https://code.visualstudio.com/api/references/vscode-api#Memento) API.  It uses SqlLite database files, one for global data and one per workspace. Location varies per platform, e.g. in Windows data lives under `%APPDATA%\Code\User`, split under a `globalStorage/` and `workspaceStorage/«workspace id»/` (OSX root would be `~/Library/Application Support/Code/User`, Linux's `~/.config/Code/User/`)

Today, I do not support VSCode's `Sync Settings` because file locations are saved as full paths, so they are not really roaming friendly, at least not in the general case. 

I could add Export/Import commands to at least dump data as JSON content (so you can back it up).  I had a version of this for debugging, but JSON content is not exactly user-friendly, so some design would be needed for this (particularly because "Import" has to deal with data merge).

**Comment by oranger-lc** [comment]
got it! 

再次感谢~

**Comment by damolinx** [comment]
This should give you a way to export data and import it if needed. It should be in 0.4.7 that I just released.
https://github.com/damolinx/vscode-bookmarks/commit/fb707d2bbac41134e1b169a7cdc92324e6fef904

You can "Export" `Global` or current `Workspace` nodes (note that a workspace must be open for its data to be loaded, so I cannot export ALL workspaces). Export dumps the bookmark data into a new editor, just save the file as a JSON file, and then you can "Import" that data into "Global" or current "Workspace". For data safety (e.g. to prevent unintended data overrides), an import always happens into a folder named `Import_#`. You can drag and drop nodes as needed after that.
