### ISSUE TITLE
bug removing folder

### ISSUE THREAD

**Issue by melissad87** [damolinx/vscode-bookmarks#6]
I usually copy-paste my GitLab branch name as the folder name. This results in an example like this: fix/AP-8714_dialog-modification-adresse_mettre-au-standard

When the folder is created in the application, the fix/ part is removed. However, all folders created this way seem to bug out, as nothing happens when I try to delete them.

The only way to delete them is by completely emptying the workspace folders.

**Comment by damolinx** [comment]
Fixing the issue on 0.4.9. A couple of caveats, due to time constraints:
-  Performed basic verification of scenarios (add/remove/move/drag-and-drop). I will verify rest of the features as time allows it.
-  Cannot look into fixing retroactively, i.e. if a folder is broken it will remain as such (because of the nature of the bug, not even sure I would be able to fix either way).  It seems you have been resetting your bookmarks so might not be a major issue.

Let me know if you run into any issues.

**Comment by melissad87** [comment]
confirm it's fixed, thnak you
